Add __DIR__ to fix not launched as bin/imbolauncher
imbo/imbolauncher pull request #8
Opened 2016-12-09 12:03 UTC by matslindh

If imbolauncher is invoked outside of its own homedir (for example through an absolute path or inside the `bin` directory itself), the existing require will fail - as it uses a relative import from the CWD.

2016-12-09 14:16 UTC, christeredvartsen requested changes
When installing `imbo/imbolauncher` using composer, as in having `imbo/imbolauncher` as a requirement, composer will create a symlink to `../imbo/imbolauncher/bin/imbolauncher` in the `vendor/bin` directory.

The current path will work both on a local installation, and when installed in the above fashion.

By adding the `__DIR__ . '/../` part only the local installation will work as installed packages don't get their own vendor directories.

2016-12-09 22:55 UTC, matslindh commented
I've updated the PR by searching for a vendor dir, as this will work regardless of the CWD when the command is invoked, as long as the dependencies has been installed (either after a git clone, after a require: in a composer.json or part of a create-project composer command). I still want to test this fix on Windows before making it final.

2016-12-12 10:07 UTC, matslindh commented
Works properly on windows as well.

2016-12-12 14:24 UTC, matslindh commented
(at least now it does)

2016-12-12 20:28 UTC, merged